### ISSUE TITLE
Destination path error occurs when running ansible-playbook for datadelivery-prod 

### ISSUE THREAD

**Issue by gsteffen1921** [Duke-GCB/gcb-ansible-roles#86]
Hitting error at build_docker_image.  Error below.
******************************************************************** 
TASK [build_docker_image : Clone the Git repo at the provided version] *********************************************************************
fatal: [vlp-datadelivery.dhe.duke.edu]: FAILED! => {"changed": false, "cmd": "/bin/git clone --origin origin https://github.com/Duke-GCB/D4S2.git /tmp/build-docker-image-src/d4s2-1.7.2", "msg": "fatal: destination path '/tmp/build-docker-image-src/d4s2-1.7.2' already exists and is not an empty directory.", "rc": 128, "stderr": "fatal: destination path '/tmp/build-docker-image-src/d4s2-1.7.2' already exists and is not an empty directory.\n", "stderr_lines": ["fatal: destination path '/tmp/build-docker-image-src/d4s2-1.7.2' already exists and is not an empty directory."], "stdout": "", "stdout_lines": []}_
***********************************************************************
Note: Removing the directory d4s2-1.7.2 fixes the issue.

**Comment by johnbradley** [comment]
The error is coming from the `git` command line program called from the ansible `git` module:
https://github.com/Duke-GCB/gcb-ansible-roles/blob/4d4cb5161a81b8cf2d05f53ab00bb93d14dece3d/build_docker_image/tasks/main.yml#L10-L14

I have been unable to reproduce this error by just running the playbook.
I think this problem only occurs when two users are involved. 
The first user runs the playbook which clones the repo.
The second user runs the playbook and the `git` module decides to run `git clone`.
Since the directory already exists this command fails.
